/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AuthController,
  AuthControllerInterface,
} from "../AuthController";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "getAuth",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "setAuth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AuthController__factory {
  static readonly abi = _abi;
  static createInterface(): AuthControllerInterface {
    return new utils.Interface(_abi) as AuthControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AuthController {
    return new Contract(address, _abi, signerOrProvider) as AuthController;
  }
}
